#!/usr/bin/env bash
# PAHLAWAN ROLEPLAY - VPS Bootstrap Script
set -euo pipefail
DRY_RUN=0
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=1 ;;
        --help|-h) sed -n '2,30p' "$0"; exit 0 ;;
        *) echo "Unknown arg: $arg"; exit 1 ;;
    esac
done
log()  { echo -e "\033[1;34m[bootstrap]\033[0m $*"; }
warn() { echo -e "\033[1;33m[WARN]\033[0m $*"; }
fail() { echo -e "\033[1;31m[FAIL]\033[0m $*" >&2; exit 1; }
run() {
    if [ "$DRY_RUN" = "1" ]; then
        echo -e "\033[2m[dry-run]\033[0m $*"
    else
        eval "$@"
    fi
}
require_root() { [ "$(id -u)" -eq 0 ] || fail "Butuh root"; }
detect_os() { . /etc/os-release; [ "$VERSION_ID" = "22.04" ] || fail "Bukan Ubuntu 22.04"; }
random_password() { tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32; }
require_root
detect_os
PAHLAWAN_DB_PASSWORD_VAL="XXPAHLAWANXX"
PTERODACTYL_DB_PASSWORD_VAL="XXPTERODACTYLXX"
mkdir -p /opt/pahlawan-roleplay
SECRETS_FILE_PATH="/opt/pahlawan-roleplay/.secrets-bootstrap"
if [ "$DRY_RUN" = "0" ]; then
    cat > "$SECRETS_FILE_PATH" <<SECRETS_EOF
# Generated by bootstrap-vps.sh pada $(date)
PAHLAWAN_DB_PASSWORD=${PAHLAWAN_DB_PASSWORD_VAL}
PTERODACTYL_DB_PASSWORD=${PTERODACTYL_DB_PASSWORD_VAL}
SECRETS_EOF
    chmod 600 "$SECRETS_FILE_PATH"
    warn "Passwords di $SECRETS_FILE_PATH. Catat & hapus setelah selesai."
fi
log "Selesai pre-flight."
