new Text:ThurXProjectTD[8];

CreateThurXProjectTD()
{
    ThurXProjectTD[0] = TextDrawCreate(-1.000000, -1.000000, "ld_dual:white");
	TextDrawFont(ThurXProjectTD[0], 4);
	TextDrawLetterSize(ThurXProjectTD[0], 0.600000, 2.000000);
	TextDrawTextSize(ThurXProjectTD[0], 641.000000, 449.500000);
	TextDrawSetOutline(ThurXProjectTD[0], 1);
	TextDrawSetShadow(ThurXProjectTD[0], 0);
	TextDrawAlignment(ThurXProjectTD[0], 1);
	TextDrawColor(ThurXProjectTD[0], 255);
	TextDrawBackgroundColor(ThurXProjectTD[0], 255);
	TextDrawBoxColor(ThurXProjectTD[0], 10);
	TextDrawUseBox(ThurXProjectTD[0], 1);
	TextDrawSetProportional(ThurXProjectTD[0], 1);
	TextDrawSetSelectable(ThurXProjectTD[0], 0);

	ThurXProjectTD[1] = TextDrawCreate(320.000000, 248.000000, "T H U R X P R O J E C T");
	TextDrawFont(ThurXProjectTD[1], 2);
	TextDrawLetterSize(ThurXProjectTD[1], 0.112498, 0.850000);
	TextDrawTextSize(ThurXProjectTD[1], 600.000000, 185.500000);
	TextDrawSetOutline(ThurXProjectTD[1], 0);
	TextDrawSetShadow(ThurXProjectTD[1], 0);
	TextDrawAlignment(ThurXProjectTD[1], 2);
	TextDrawColor(ThurXProjectTD[1], -1);
	TextDrawBackgroundColor(ThurXProjectTD[1], 255);
	TextDrawBoxColor(ThurXProjectTD[1], 50);
	TextDrawUseBox(ThurXProjectTD[1], 0);
	TextDrawSetProportional(ThurXProjectTD[1], 0);
	TextDrawSetSelectable(ThurXProjectTD[1], 0);

	ThurXProjectTD[2] = TextDrawCreate(287.000000, 199.000000, "ld_pool:ball");
	TextDrawFont(ThurXProjectTD[2], 4);
	TextDrawLetterSize(ThurXProjectTD[2], 0.600000, 2.000000);
	TextDrawTextSize(ThurXProjectTD[2], 31.500000, 38.000000);
	TextDrawSetOutline(ThurXProjectTD[2], 0);
	TextDrawSetShadow(ThurXProjectTD[2], 4);
	TextDrawAlignment(ThurXProjectTD[2], 1);
	TextDrawColor(ThurXProjectTD[2], -1);
	TextDrawBackgroundColor(ThurXProjectTD[2], 255);
	TextDrawBoxColor(ThurXProjectTD[2], 50);
	TextDrawUseBox(ThurXProjectTD[2], 1);
	TextDrawSetProportional(ThurXProjectTD[2], 1);
	TextDrawSetSelectable(ThurXProjectTD[2], 0);

	ThurXProjectTD[3] = TextDrawCreate(321.000000, 199.000000, "ld_pool:ball");
	TextDrawFont(ThurXProjectTD[3], 4);
	TextDrawLetterSize(ThurXProjectTD[3], 0.600000, 2.000000);
	TextDrawTextSize(ThurXProjectTD[3], 31.500000, 38.000000);
	TextDrawSetOutline(ThurXProjectTD[3], 1);
	TextDrawSetShadow(ThurXProjectTD[3], 0);
	TextDrawAlignment(ThurXProjectTD[3], 1);
	TextDrawColor(ThurXProjectTD[3], -1);
	TextDrawBackgroundColor(ThurXProjectTD[3], 255);
	TextDrawBoxColor(ThurXProjectTD[3], 50);
	TextDrawUseBox(ThurXProjectTD[3], 1);
	TextDrawSetProportional(ThurXProjectTD[3], 1);
	TextDrawSetSelectable(ThurXProjectTD[3], 0);

	ThurXProjectTD[4] = TextDrawCreate(289.000000, 202.000000, "ld_pool:ball");
	TextDrawFont(ThurXProjectTD[4], 4);
	TextDrawLetterSize(ThurXProjectTD[4], 0.600000, 2.000000);
	TextDrawTextSize(ThurXProjectTD[4], 27.500000, 32.500000);
	TextDrawSetOutline(ThurXProjectTD[4], 0);
	TextDrawSetShadow(ThurXProjectTD[4], 4);
	TextDrawAlignment(ThurXProjectTD[4], 1);
	TextDrawColor(ThurXProjectTD[4], 255);
	TextDrawBackgroundColor(ThurXProjectTD[4], 255);
	TextDrawBoxColor(ThurXProjectTD[4], 50);
	TextDrawUseBox(ThurXProjectTD[4], 1);
	TextDrawSetProportional(ThurXProjectTD[4], 1);
	TextDrawSetSelectable(ThurXProjectTD[4], 0);

	ThurXProjectTD[5] = TextDrawCreate(323.000000, 202.000000, "ld_pool:ball");
	TextDrawFont(ThurXProjectTD[5], 4);
	TextDrawLetterSize(ThurXProjectTD[5], 0.600000, 2.000000);
	TextDrawTextSize(ThurXProjectTD[5], 27.500000, 32.500000);
	TextDrawSetOutline(ThurXProjectTD[5], 0);
	TextDrawSetShadow(ThurXProjectTD[5], 4);
	TextDrawAlignment(ThurXProjectTD[5], 1);
	TextDrawColor(ThurXProjectTD[5], 255);
	TextDrawBackgroundColor(ThurXProjectTD[5], 255);
	TextDrawBoxColor(ThurXProjectTD[5], 50);
	TextDrawUseBox(ThurXProjectTD[5], 1);
	TextDrawSetProportional(ThurXProjectTD[5], 1);
	TextDrawSetSelectable(ThurXProjectTD[5], 0);

	ThurXProjectTD[6] = TextDrawCreate(295.000000, 216.000000, "ld_pool:ball");
	TextDrawFont(ThurXProjectTD[6], 4);
	TextDrawLetterSize(ThurXProjectTD[6], 0.600000, 2.000000);
	TextDrawTextSize(ThurXProjectTD[6], 15.500000, 18.500000);
	TextDrawSetOutline(ThurXProjectTD[6], 0);
	TextDrawSetShadow(ThurXProjectTD[6], 4);
	TextDrawAlignment(ThurXProjectTD[6], 1);
	TextDrawColor(ThurXProjectTD[6], -1);
	TextDrawBackgroundColor(ThurXProjectTD[6], 255);
	TextDrawBoxColor(ThurXProjectTD[6], 50);
	TextDrawUseBox(ThurXProjectTD[6], 1);
	TextDrawSetProportional(ThurXProjectTD[6], 1);
	TextDrawSetSelectable(ThurXProjectTD[6], 0);

	ThurXProjectTD[7] = TextDrawCreate(329.000000, 216.000000, "ld_pool:ball");
	TextDrawFont(ThurXProjectTD[7], 4);
	TextDrawLetterSize(ThurXProjectTD[7], 0.600000, 2.000000);
	TextDrawTextSize(ThurXProjectTD[7], 15.500000, 18.500000);
	TextDrawSetOutline(ThurXProjectTD[7], 0);
	TextDrawSetShadow(ThurXProjectTD[7], 4);
	TextDrawAlignment(ThurXProjectTD[7], 1);
	TextDrawColor(ThurXProjectTD[7], -1);
	TextDrawBackgroundColor(ThurXProjectTD[7], 255);
	TextDrawBoxColor(ThurXProjectTD[7], 50);
	TextDrawUseBox(ThurXProjectTD[7], 1);
	TextDrawSetProportional(ThurXProjectTD[7], 1);
	TextDrawSetSelectable(ThurXProjectTD[7], 0);
}

ShowThurXProjectTD(playerid)
{
    for (new i = 0; i < sizeof(ThurXProjectTD); i++)
    {
        TextDrawShowForPlayer(playerid, ThurXProjectTD[i]);
    }
    return 1;
}

HideThurXProjectTD(playerid)
{
    for (new i = 0; i < sizeof(ThurXProjectTD); i++)
    {
        TextDrawHideForPlayer(playerid, ThurXProjectTD[i]);
    }
    return 1;
}